// ============================================
// Corcoran Lifestyle Properties — Inventory
// This file is auto-generated by admin.html
// Go to admin.html → Export tab → Copy & paste here
// ============================================

// No homes exported yet — static defaults shown on homepage
// Once you export from admin.html, replace this entire file.

window.CLP_SETTINGS = {
“name”: “Corcoran Lifestyle Properties”,
“wa”: “+12515010068”,
“tagline”: “Low down payments · Easy seller financing · Rent-to-own · Nationwide delivery”
};

window.CLP_HOMES = [];
// Empty = homepage shows static hardcoded cards
// Fill via admin.html Export tab
